--- #YAML:1.0
name:               Finance-FXCM-Simple
version:            0.008
abstract:           A synchronous wrapper to the FXCM ForexConnect API which is simple to use.
author:
    - João Costa <joaocosta@zonalivre.org>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Scalar::Util:  0
    Test::More:    0
requires:
    YAML::Syck:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
