---
abstract: 'A synchronous wrapper to the FXCM ForexConnect API which is simple to use.'
author:
  - 'João Costa <joaocosta@zonalivre.org>'
build_requires:
  Data::Dumper: 0
  Scalar::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0.34
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-FXCM-Simple
requires:
  XSLoader: 0
  YAML::Syck: 0
  strict: 0
  warnings: 0
version: 0.010
